### ISSUE TITLE
Crash when setting `js.strict` in GraalVM 22.2

### ISSUE THREAD

**Issue by AndrewKvalheim** [Gubaer/josm-scripting-plugin#101]
With plugin version 0.2.7 in JOSM 18700 on GraalVM 22.2 or 22.3, the plugin crashes when [setting `js.strict`](https://github.com/Gubaer/josm-scripting-plugin/blob/v0.2.7/src/main/java/org/openstreetmap/josm/plugins/scripting/graalvm/GraalVMFacade.java#L65-L66):

```
java.lang.IllegalArgumentException: Could not find option with name js.strict.
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineException.illegalArgument(PolyglotEngineException.java:131)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.OptionValuesImpl.failNotFound(OptionValuesImpl.java:274)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.parseOptions(PolyglotEngineImpl.java:736)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:313)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:288)
	at org.graalvm.sdk/org.graalvm.polyglot.Engine$Builder.build(Engine.java:625)
	at org.graalvm.sdk/org.graalvm.polyglot.Context$Builder.build(Context.java:1851)
	at org.openstreetmap.josm.plugins.scripting.graalvm.GraalVMFacade.initContext(GraalVMFacade.java:91)
	at org.openstreetmap.josm.plugins.scripting.graalvm.GraalVMFacade.<init>(GraalVMFacade.java:97)
	at org.openstreetmap.josm.plugins.scripting.graalvm.GraalVMFacadeFactory.createGraalVMFacade(GraalVMFacadeFactory.java:42)
	at org.openstreetmap.josm.plugins.scripting.graalvm.GraalVMFacadeFactory.getOrCreateGraalVMFacade(GraalVMFacadeFactory.java:53)
	at org.openstreetmap.josm.plugins.scripting.ui.console.ScriptEditorModel.selectDefaultScriptEngine(ScriptEditorModel.java:50)
	at org.openstreetmap.josm.plugins.scripting.ui.console.ScriptEditorModel.<init>(ScriptEditorModel.java:72)
	at org.openstreetmap.josm.plugins.scripting.ui.console.ScriptEditor.build(ScriptEditor.java:84)
	at org.openstreetmap.josm.plugins.scripting.ui.console.ScriptEditor.<init>(ScriptEditor.java:116)
	at org.openstreetmap.josm.plugins.scripting.ui.console.ScriptingConsolePanel.buildInputPanel(ScriptingConsolePanel.java:51)
	at org.openstreetmap.josm.plugins.scripting.ui.console.ScriptingConsolePanel.buildSplitPane(ScriptingConsolePanel.java:79)
	at org.openstreetmap.josm.plugins.scripting.ui.console.ScriptingConsolePanel.build(ScriptingConsolePanel.java:89)
	at org.openstreetmap.josm.plugins.scripting.ui.console.ScriptingConsolePanel.<init>(ScriptingConsolePanel.java:165)
	at org.openstreetmap.josm.plugins.scripting.ui.console.ScriptingConsole.build(ScriptingConsole.java:139)
	at org.openstreetmap.josm.plugins.scripting.ui.console.ScriptingConsole.<init>(ScriptingConsole.java:102)
	at org.openstreetmap.josm.plugins.scripting.ui.console.ScriptingConsole.showScriptingConsole(ScriptingConsole.java:58)
	at org.openstreetmap.josm.plugins.scripting.ui.console.ScriptingConsole.toggleScriptingConsole(ScriptingConsole.java:92)
	at org.openstreetmap.josm.plugins.scripting.ui.ToggleConsoleAction.actionPerformed(ToggleConsoleAction.java:42)
```

This doesn’t happen with GraalVM 22.1.

**Comment by Gubaer** [comment]
Yes, I today tried to upgrade the plugin to GraalVM 22.1 and also run into this error.

Unfortunately, disabling `js.strict`  doesn't help. There's another problem: with GraalVM 22.2 the plugin somehow doesn't find the `js` engine anymore. 

I don't know yet what is going on.

**Comment by Gubaer** [comment]
Possibly related to the fact that starting with 22.2 JavaScript support is decoupled from the base GraalVM installation, see [release notes](https://www.graalvm.org/release-notes/22_2/).

**Comment by Gubaer** [comment]
Can confirm: Starting from GraalVM 22.2 the JavaScript language has to be added explicitly to your GraalVM installation.
It isn't part of the base GraalVM anymore.

Within your GraalVM installation run

```
./bin/gu install js
```

Then start JOSM with the `java` executable provided by GraalVM and use the scripting plugin.

**Comment by AndrewKvalheim** [comment]
Ah, thanks! I should have researched it more. In case it’s useful to anyone else, here’s the Nix expression:

```nix
josm.override {
  jre = graalvm17-ce.override {
    products = with graalvmCEPackages; [ js-installable-svm-java17 ];
  };
}
```
