### ISSUE TITLE
Can't use JS modules on Windows

### ISSUE THREAD

**Issue by Yogurt4** [Gubaer/josm-scripting-plugin#110]
I'm trying to get anything run from a script file, like simply running

```
import {sayHello} from 'helloworld.js'
sayHello()
```

However, I receive the following error:

```
path must not be absolute, got 'C:\Users\username\AppData\Roaming\JOSM\helloworld.js'

--------------------------------------------------------
org.openstreetmap.josm.plugins.scripting.graalvm.GraalVMEvalException: failed to eval script
	at org.openstreetmap.josm.plugins.scripting.graalvm.GraalVMFacade.eval(GraalVMFacade.java:186)
	at org.openstreetmap.josm.plugins.scripting.ui.ScriptExecutor.lambda$runScriptWithGraalEngine$2(ScriptExecutor.java:187)
...
```

See, I haven't used any absolute paths in my script, it was created by the scripting engine itself.
I've tried `./helloworld.js` for the same result.

`import {sayHello} from 'C:/Users/username/AppData/Local/JOSM/helloworld.js'` gets me the well-known "Error: URI scheme is not "file""

For `import {sayHello} from 'file://C:/Users/username/AppData/Local/JOSM/helloworld.js'` JOSM freezes for some time then I get  "Error: \\C\Users\username\AppData\Local\JOSM\helloworld.js: The network path was not found" (Note how the slashes got converted back to backslashes and removing the colon.)

**Comment by Yogurt4** [comment]
Though I think it to be a generic Windows issue, for the reference:

Identification: JOSM/1.5 (19265) Windows 10 64-Bit
OS Build number: Windows 10 Pro 22H2 (19045)
Memory Usage: 980 MB / 4050 MB (479 MB allocated, but free)
Java version: 21.0.5+11-LTS, Azul Systems, Inc., OpenJDK 64-Bit Server VM
VM arguments: [--module-path=<josm.pref>\graaljs-23.1.1\lib, --add-modules=org.graalvm.polyglot,org.graalvm.word,org.graalvm.collections]

**Comment by Gubaer** [comment]
Try a module name without file suffix `.js`, see [doc](https://gubaer.github.io/josm-scripting-plugin/docs/v3/modules.html). Last time I checked this worked.

```
import {sayHello} from 'helloworld'
sayHello()
```

**Comment by Yogurt4** [comment]
Of course, that was the first thing I've tried. Sorry I forgot to mention.
This one gives me "Error: Error reading: C:\Users\username\AppData\Roaming\JOSM\helloworld"

If I put a "helloworld" file there (without any extensions) to make it happy, the error changes to "path must not be absolute, got 'C:\Users\username\AppData\Roaming\JOSM\helloworld'"

**Comment by Gubaer** [comment]
Did you also add the **path of your module repository** to the scripting preferences in JOSM? See again the  [doc](https://gubaer.github.io/josm-scripting-plugin/docs/v3/modules.html).

**Comment by Yogurt4** [comment]
It's interesting. Of course I've started with adding the module path, as per the doc. However, it did not appear on the list below. I thought I've used an internal default (the JOSM directory). Because the error messages used the correct path (all above), I didn't care too much.

I had to revert the JDK to version 21 (due to a certificate issue) since then. I gave the module paths another try and now it got on the list. Also, my .js file was loaded correctly.

**Comment by Gubaer** [comment]
Ok, good to known!
